# Generated by Django 4.2.16 on 2024-10-03 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion_personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=30)),
                ('residencia', models.CharField(max_length=150)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=20)),
                ('id_informacion_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extension.informacion_personal')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_laboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_perfil', models.CharField(max_length=40)),
                ('expectativa_salario', models.FloatField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hoja_vida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoja_vida', models.FileField(upload_to='hojas_vida/')),
                ('informacion_extraida', models.JSONField()),
                ('id_perfil_laboral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extension.perfil_laboral')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('id_informacion_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extension.informacion_personal')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
                ('id_perfil_laboral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extension.perfil_laboral')),
            ],
        ),
    ]
